name: Release Build

on:
  workflow_dispatch:

  release:
    types: [ published ]

env:
  GIT_PREVIOUS_SUCCESSFUL_COMMIT: ${{ github.event.before }}

jobs:
  build:
    uses: ryderbelserion/ryderbelserion/.github/workflows/build.yml@main

    with:
      platforms: "modrinth"
      status: "release"
      branch: main

    secrets:
      webhook: ${{ secrets.BUILD_WEBHOOK }}
      modrinth_token: ${{ secrets.MODRINTH_TOKEN }}
      hangar_token: ${{ secrets.HANGAR_KEY }}