name: Snapshot Build

on:
  workflow_dispatch:

  push:
    branches:
      - main

env:
  GIT_PREVIOUS_SUCCESSFUL_COMMIT: ${{ github.event.before }}
  version_status: "beta"

jobs:
  build:
    uses: ryderbelserion/ryderbelserion/.github/workflows/build.yml@main

    with:
      branch: main
      publish: modrinth

    secrets:
      webhook: ${{ secrets.CS_WEBHOOK }}
      modrinth_token: ${{ secrets.MODRINTH_TOKEN }}
      hangar_token: ${{ secrets.HANGAR_KEY }}